FROM debian:bookworm-slim AS builder

RUN apt-get update && \
    apt-get -y --no-install-recommends install \
        ca-certificates \
        cmake \
        g++ \
        gcc \
        libboost1.81-all-dev \
        libbz2-dev \
        liblua5.4-dev \
        libtbb-dev \
        libxml2-dev \
        libzip-dev \
        lua5.4 \
        make \
        pkg-config && \
    rm -rf /var/lib/apt/lists/*

COPY . /src
WORKDIR /src

RUN export CXXFLAGS="-Wno-array-bounds -Wno-uninitialized -Wno-stringop-overflow -O3 -march=x86-64 -mtune=generic" && \
    mkdir -p build && \
    cd build && \
    cmake .. \
        -DCMAKE_BUILD_TYPE=Release \
        -DENABLE_ASSERTIONS=Off \
        -DENABLE_LTO=Off \
        -DCMAKE_CXX_FLAGS_RELEASE="-O3 -DNDEBUG -march=x86-64" \
        -DCMAKE_EXE_LINKER_FLAGS="-s" && \
    make -j2 osrm-routed && \
    strip osrm-routed

FROM debian:bookworm-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends awscli && \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder /src/build/osrm-routed /usr/local/bin/osrm-routed

CMD ["aws", "s3", "cp", "/usr/local/bin/osrm-routed", "s3://my-osrm-data-715/software/osrm-routed"]
